// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fnthreads
int fnthreads(const int& nthread);
RcppExport SEXP _AsyPeer_fnthreads(SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fnthreads(nthread));
    return rcpp_result_gen;
END_RCPP
}
// highlowstat1
List highlowstat1(const Eigen::MatrixXd& X, const std::vector<Eigen::ArrayXXd>& G, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int& ngroup, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_highlowstat1(SEXP XSEXP, SEXP GSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP ngroupSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(highlowstat1(X, G, cumsn, nvec, ngroup, nthread));
    return rcpp_result_gen;
END_RCPP
}
// highlowstat2
List highlowstat2(const Eigen::VectorXd& y, const Eigen::MatrixXd& X, const std::vector<Eigen::ArrayXXd>& G, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int ngroup, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_highlowstat2(SEXP ySEXP, SEXP XSEXP, SEXP GSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP ngroupSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(highlowstat2(y, X, G, cumsn, nvec, ngroup, nthread));
    return rcpp_result_gen;
END_RCPP
}
// peeravgpower
Eigen::MatrixXd peeravgpower(const std::vector<Eigen::MatrixXd>& G, const Eigen::ArrayXXd& V, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int& power, const int& nthread);
RcppExport SEXP _AsyPeer_peeravgpower(SEXP GSEXP, SEXP VSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP powerSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type power(powerSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(peeravgpower(G, V, cumsn, nvec, power, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fcheckrankEigen
Eigen::Array<bool, Eigen::Dynamic, 1> fcheckrankEigen(const Eigen::MatrixXd& X, const double& tol);
RcppExport SEXP _AsyPeer_fcheckrankEigen(SEXP XSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fcheckrankEigen(X, tol));
    return rcpp_result_gen;
END_RCPP
}
// fassignfold
Eigen::ArrayXi fassignfold(const Eigen::ArrayXi& ddgroup, const int& nfold);
RcppExport SEXP _AsyPeer_fassignfold(SEXP ddgroupSEXP, SEXP nfoldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddgroup(ddgroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type nfold(nfoldSEXP);
    rcpp_result_gen = Rcpp::wrap(fassignfold(ddgroup, nfold));
    return rcpp_result_gen;
END_RCPP
}
// Demean_separate
Eigen::ArrayXXd Demean_separate(const Eigen::ArrayXXd& X, const Eigen::ArrayXi& cumsn, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const int& nthread);
RcppExport SEXP _AsyPeer_Demean_separate(SEXP XSEXP, SEXP cumsnSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Demean_separate(X, cumsn, lIso, lnIso, nthread));
    return rcpp_result_gen;
END_RCPP
}
// Demean_common
Eigen::ArrayXXd Demean_common(const Eigen::ArrayXXd& X, const Eigen::ArrayXi& cumsn, const int& nthread);
RcppExport SEXP _AsyPeer_Demean_common(SEXP XSEXP, SEXP cumsnSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Demean_common(X, cumsn, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fGnormalise
std::vector<Eigen::ArrayXXd> fGnormalise(std::vector<Eigen::ArrayXXd>& G, const int& nthread);
RcppExport SEXP _AsyPeer_fGnormalise(SEXP GSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fGnormalise(G, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fFstat
Rcpp::List fFstat(const Eigen::MatrixXd& y, const Eigen::MatrixXd& X, const Eigen::VectorXi& index, const Eigen::ArrayXi& cumsn, const int& HAC, const int& nthread);
RcppExport SEXP _AsyPeer_fFstat(SEXP ySEXP, SEXP XSEXP, SEXP indexSEXP, SEXP cumsnSEXP, SEXP HACSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fFstat(y, X, index, cumsn, HAC, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fKPstat
Rcpp::List fKPstat(const Eigen::MatrixXd& endo_, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z_, const Eigen::VectorXi& index, const Eigen::ArrayXd& cumsn, const int& HAC);
RcppExport SEXP _AsyPeer_fKPstat(SEXP endo_SEXP, SEXP XSEXP, SEXP Z_SEXP, SEXP indexSEXP, SEXP cumsnSEXP, SEXP HACSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo_(endo_SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z_(Z_SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    rcpp_result_gen = Rcpp::wrap(fKPstat(endo_, X, Z_, index, cumsn, HAC));
    return rcpp_result_gen;
END_RCPP
}
// fdataML
Rcpp::List fdataML(const Eigen::ArrayXd& y, const Eigen::ArrayXXd& X, const Eigen::ArrayXi& group, const Eigen::ArrayXi& IDi, const std::vector<Eigen::ArrayXd>& gij, const std::vector<Eigen::ArrayXi>& idpeer, const Eigen::ArrayXi& ddni, const Eigen::ArrayXi& ddncs, const Eigen::ArrayXi& ncs, const int& nthread);
RcppExport SEXP _AsyPeer_fdataML(SEXP ySEXP, SEXP XSEXP, SEXP groupSEXP, SEXP IDiSEXP, SEXP gijSEXP, SEXP idpeerSEXP, SEXP ddniSEXP, SEXP ddncsSEXP, SEXP ncsSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type IDi(IDiSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXd>& >::type gij(gijSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type idpeer(idpeerSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddni(ddniSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddncs(ddncsSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ncs(ncsSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fdataML(y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fInstChecky
Eigen::ArrayXXd fInstChecky(const Eigen::ArrayXXd& rhoddX, const Eigen::ArrayXi& ddni, const int& nthread);
RcppExport SEXP _AsyPeer_fInstChecky(SEXP rhoddXSEXP, SEXP ddniSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type rhoddX(rhoddXSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddni(ddniSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fInstChecky(rhoddX, ddni, nthread));
    return rcpp_result_gen;
END_RCPP
}
// gmm_obj
double gmm_obj(const double& betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X_iso, const Eigen::MatrixXd& X_niso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& c_gamma, const Eigen::ArrayXi& nc_gamma, const int& S);
RcppExport SEXP _AsyPeer_gmm_obj(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP X_isoSEXP, SEXP X_nisoSEXP, SEXP WSEXP, SEXP c_gammaSEXP, SEXP nc_gammaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_iso(X_isoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_niso(X_nisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type c_gamma(c_gammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_obj(betal, Z, y, endo, X_iso, X_niso, W, c_gamma, nc_gamma, S));
    return rcpp_result_gen;
END_RCPP
}
// gmm_obj_nospil
double gmm_obj_nospil(const double& betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X_iso, const Eigen::MatrixXd& X_niso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& c_gamma, const Eigen::ArrayXi& nc_gamma, const int& S);
RcppExport SEXP _AsyPeer_gmm_obj_nospil(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP X_isoSEXP, SEXP X_nisoSEXP, SEXP WSEXP, SEXP c_gammaSEXP, SEXP nc_gammaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_iso(X_isoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_niso(X_nisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type c_gamma(c_gammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_obj_nospil(betal, Z, y, endo, X_iso, X_niso, W, c_gamma, nc_gamma, S));
    return rcpp_result_gen;
END_RCPP
}
// W_optimal
Eigen::MatrixXd W_optimal(const double& betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X_iso, const Eigen::MatrixXd& X_niso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::VectorXd& cumsn, const int& dfiso, const int& dfniso, const int& HAC, const Eigen::ArrayXi& c_gamma, const Eigen::ArrayXi& nc_gamma, const int& S);
RcppExport SEXP _AsyPeer_W_optimal(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP X_isoSEXP, SEXP X_nisoSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP c_gammaSEXP, SEXP nc_gammaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_iso(X_isoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_niso(X_nisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type c_gamma(c_gammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(W_optimal(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S));
    return rcpp_result_gen;
END_RCPP
}
// W_optimal_nospil
Eigen::MatrixXd W_optimal_nospil(const double& betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X_iso, const Eigen::MatrixXd& X_niso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::VectorXd& cumsn, const int& dfiso, const int& dfniso, const int& HAC, const Eigen::ArrayXi& c_gamma, const Eigen::ArrayXi& nc_gamma, const int& S);
RcppExport SEXP _AsyPeer_W_optimal_nospil(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP X_isoSEXP, SEXP X_nisoSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP c_gammaSEXP, SEXP nc_gammaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_iso(X_isoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_niso(X_nisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type c_gamma(c_gammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(W_optimal_nospil(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S));
    return rcpp_result_gen;
END_RCPP
}
// compute_estimate
Rcpp::List compute_estimate(const double& betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X_iso, const Eigen::MatrixXd& X_niso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::VectorXd& cumsn, const int& dfiso, const int& dfniso, const int& HAC, const Eigen::ArrayXi& c_gamma, const Eigen::ArrayXi& nc_gamma, const int& S);
RcppExport SEXP _AsyPeer_compute_estimate(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP X_isoSEXP, SEXP X_nisoSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP c_gammaSEXP, SEXP nc_gammaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_iso(X_isoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_niso(X_nisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type c_gamma(c_gammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_estimate(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S));
    return rcpp_result_gen;
END_RCPP
}
// compute_estimate_nospil
Rcpp::List compute_estimate_nospil(const double& betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X_iso, const Eigen::MatrixXd& X_niso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::VectorXd& cumsn, const int& dfiso, const int& dfniso, const int& HAC, const Eigen::ArrayXi& c_gamma, const Eigen::ArrayXi& nc_gamma, const int& S);
RcppExport SEXP _AsyPeer_compute_estimate_nospil(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP X_isoSEXP, SEXP X_nisoSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP c_gammaSEXP, SEXP nc_gammaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_iso(X_isoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_niso(X_nisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type c_gamma(c_gammaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_estimate_nospil(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S));
    return rcpp_result_gen;
END_RCPP
}
// fNashE
int fNashE(Eigen::Map<Eigen::VectorXd> y, const Eigen::ArrayXd& alpha, const std::vector<Eigen::MatrixXd>& G, const Eigen::ArrayXd& peffects, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const std::vector<Eigen::ArrayXi>& idpeer, const Eigen::ArrayXi& d, const int& ngroup, const double& tol, const int& maxit, const unsigned int& nthread, const bool& print);
RcppExport SEXP _AsyPeer_fNashE(SEXP ySEXP, SEXP alphaSEXP, SEXP GSEXP, SEXP peffectsSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP idpeerSEXP, SEXP dSEXP, SEXP ngroupSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP nthreadSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type peffects(peffectsSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type idpeer(idpeerSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    Rcpp::traits::input_parameter< const bool& >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(fNashE(y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AsyPeer_fnthreads", (DL_FUNC) &_AsyPeer_fnthreads, 1},
    {"_AsyPeer_highlowstat1", (DL_FUNC) &_AsyPeer_highlowstat1, 6},
    {"_AsyPeer_highlowstat2", (DL_FUNC) &_AsyPeer_highlowstat2, 7},
    {"_AsyPeer_peeravgpower", (DL_FUNC) &_AsyPeer_peeravgpower, 6},
    {"_AsyPeer_fcheckrankEigen", (DL_FUNC) &_AsyPeer_fcheckrankEigen, 2},
    {"_AsyPeer_fassignfold", (DL_FUNC) &_AsyPeer_fassignfold, 2},
    {"_AsyPeer_Demean_separate", (DL_FUNC) &_AsyPeer_Demean_separate, 5},
    {"_AsyPeer_Demean_common", (DL_FUNC) &_AsyPeer_Demean_common, 3},
    {"_AsyPeer_fGnormalise", (DL_FUNC) &_AsyPeer_fGnormalise, 2},
    {"_AsyPeer_fFstat", (DL_FUNC) &_AsyPeer_fFstat, 6},
    {"_AsyPeer_fKPstat", (DL_FUNC) &_AsyPeer_fKPstat, 6},
    {"_AsyPeer_fdataML", (DL_FUNC) &_AsyPeer_fdataML, 10},
    {"_AsyPeer_fInstChecky", (DL_FUNC) &_AsyPeer_fInstChecky, 3},
    {"_AsyPeer_gmm_obj", (DL_FUNC) &_AsyPeer_gmm_obj, 10},
    {"_AsyPeer_gmm_obj_nospil", (DL_FUNC) &_AsyPeer_gmm_obj_nospil, 10},
    {"_AsyPeer_W_optimal", (DL_FUNC) &_AsyPeer_W_optimal, 16},
    {"_AsyPeer_W_optimal_nospil", (DL_FUNC) &_AsyPeer_W_optimal_nospil, 16},
    {"_AsyPeer_compute_estimate", (DL_FUNC) &_AsyPeer_compute_estimate, 16},
    {"_AsyPeer_compute_estimate_nospil", (DL_FUNC) &_AsyPeer_compute_estimate_nospil, 16},
    {"_AsyPeer_fNashE", (DL_FUNC) &_AsyPeer_fNashE, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_AsyPeer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
