// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fnthreads
int fnthreads(const int& nthread);
RcppExport SEXP _AsyPeer_fnthreads(SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fnthreads(nthread));
    return rcpp_result_gen;
END_RCPP
}
// highlowstat1
List highlowstat1(const Eigen::MatrixXd& X, const std::vector<Eigen::ArrayXXd>& G, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int& ngroup, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_highlowstat1(SEXP XSEXP, SEXP GSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP ngroupSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(highlowstat1(X, G, cumsn, nvec, ngroup, nthread));
    return rcpp_result_gen;
END_RCPP
}
// highlowstat2
List highlowstat2(const Eigen::VectorXd& y, const Eigen::MatrixXd& X, const std::vector<Eigen::ArrayXXd>& G, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int ngroup, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_highlowstat2(SEXP ySEXP, SEXP XSEXP, SEXP GSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP ngroupSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(highlowstat2(y, X, G, cumsn, nvec, ngroup, nthread));
    return rcpp_result_gen;
END_RCPP
}
// peeravgpower
Eigen::MatrixXd peeravgpower(const std::vector<Eigen::MatrixXd>& G, const Eigen::ArrayXXd& V, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int& power, const int& nthread);
RcppExport SEXP _AsyPeer_peeravgpower(SEXP GSEXP, SEXP VSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP powerSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type power(powerSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(peeravgpower(G, V, cumsn, nvec, power, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fcheckrankEigen
Eigen::Array<bool, Eigen::Dynamic, 1> fcheckrankEigen(const Eigen::MatrixXd& X, const double& tol);
RcppExport SEXP _AsyPeer_fcheckrankEigen(SEXP XSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fcheckrankEigen(X, tol));
    return rcpp_result_gen;
END_RCPP
}
// fassignfold
Eigen::ArrayXi fassignfold(const Eigen::ArrayXi& ddgroup, const int& nfold);
RcppExport SEXP _AsyPeer_fassignfold(SEXP ddgroupSEXP, SEXP nfoldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddgroup(ddgroupSEXP);
    Rcpp::traits::input_parameter< const int& >::type nfold(nfoldSEXP);
    rcpp_result_gen = Rcpp::wrap(fassignfold(ddgroup, nfold));
    return rcpp_result_gen;
END_RCPP
}
// Demean_separate
Eigen::ArrayXXd Demean_separate(const Eigen::ArrayXXd& X, const Eigen::ArrayXi& cumsn, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const int& nthread);
RcppExport SEXP _AsyPeer_Demean_separate(SEXP XSEXP, SEXP cumsnSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Demean_separate(X, cumsn, lIso, lnIso, nthread));
    return rcpp_result_gen;
END_RCPP
}
// Demean_common
Eigen::ArrayXXd Demean_common(const Eigen::ArrayXXd& X, const Eigen::ArrayXi& cumsn, const int& nthread);
RcppExport SEXP _AsyPeer_Demean_common(SEXP XSEXP, SEXP cumsnSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Demean_common(X, cumsn, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fGnormalise
std::vector<Eigen::ArrayXXd> fGnormalise(std::vector<Eigen::ArrayXXd>& G, const int& nthread);
RcppExport SEXP _AsyPeer_fGnormalise(SEXP GSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fGnormalise(G, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fFstat
Rcpp::List fFstat(const Eigen::MatrixXd& y, const Eigen::MatrixXd& X, const Eigen::VectorXi& index, const Eigen::ArrayXi& cumsn, const int& HAC, const int& nthread);
RcppExport SEXP _AsyPeer_fFstat(SEXP ySEXP, SEXP XSEXP, SEXP indexSEXP, SEXP cumsnSEXP, SEXP HACSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fFstat(y, X, index, cumsn, HAC, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fKPstat
Rcpp::List fKPstat(const Eigen::MatrixXd& endo_, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z_, const Eigen::VectorXi& index, const Eigen::ArrayXd& cumsn, const int& HAC);
RcppExport SEXP _AsyPeer_fKPstat(SEXP endo_SEXP, SEXP XSEXP, SEXP Z_SEXP, SEXP indexSEXP, SEXP cumsnSEXP, SEXP HACSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo_(endo_SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z_(Z_SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    rcpp_result_gen = Rcpp::wrap(fKPstat(endo_, X, Z_, index, cumsn, HAC));
    return rcpp_result_gen;
END_RCPP
}
// fCESdata
Eigen::ArrayXXd fCESdata(const Eigen::ArrayXXd& X, const Eigen::ArrayXd& y, const Eigen::ArrayXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const int& n, const int& Kx, const int& S, const double& rho, const bool& FE, const bool& deriv, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_fCESdata(SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP nSEXP, SEXP KxSEXP, SEXP SSEXP, SEXP rhoSEXP, SEXP FESEXP, SEXP derivSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const bool& >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESdata(X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, nvec, yFMiMa, zFMiMa, n, Kx, S, rho, FE, deriv, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fCESplotdata
Rcpp::List fCESplotdata(const Eigen::ArrayXd& gridrho, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::VectorXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const Eigen::ArrayXi& idXiso, const Eigen::ArrayXi& idXniso, const Eigen::ArrayXi& sel, const bool& FE, const int& maxit, const double& eps_f, const double& eps_g, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_fCESplotdata(SEXP gridrhoSEXP, SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP idXisoSEXP, SEXP idXnisoSEXP, SEXP selSEXP, SEXP FESEXP, SEXP maxitSEXP, SEXP eps_fSEXP, SEXP eps_gSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type gridrho(gridrhoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXiso(idXisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXniso(idXnisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps_g(eps_gSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESplotdata(gridrho, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, idXiso, idXniso, sel, FE, maxit, eps_f, eps_g, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fCESMain
Rcpp::List fCESMain(const Rcpp::Nullable<double> setrho, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::VectorXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const Eigen::ArrayXi& idXiso, const Eigen::ArrayXi& idXniso, const Eigen::ArrayXi& sel, const int& n, const int& Kx, const int& S, const int& HACn, const int& dfiso, const int& dfniso, const bool& FE, const double& rhomin, const double& rhomax, const int& maxit, const double& eps_f, const double& eps_g, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_fCESMain(SEXP setrhoSEXP, SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP idXisoSEXP, SEXP idXnisoSEXP, SEXP selSEXP, SEXP nSEXP, SEXP KxSEXP, SEXP SSEXP, SEXP HACnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP FESEXP, SEXP rhominSEXP, SEXP rhomaxSEXP, SEXP maxitSEXP, SEXP eps_fSEXP, SEXP eps_gSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Nullable<double> >::type setrho(setrhoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXiso(idXisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXniso(idXnisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int& >::type HACn(HACnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const double& >::type rhomin(rhominSEXP);
    Rcpp::traits::input_parameter< const double& >::type rhomax(rhomaxSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps_g(eps_gSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESMain(setrho, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, idXiso, idXniso, sel, n, Kx, S, HACn, dfiso, dfniso, FE, rhomin, rhomax, maxit, eps_f, eps_g, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fdataML
Rcpp::List fdataML(const Eigen::ArrayXd& y, const Eigen::ArrayXXd& X, const Eigen::ArrayXi& group, const Eigen::ArrayXi& IDi, const std::vector<Eigen::ArrayXd>& gij, const std::vector<Eigen::ArrayXi>& idpeer, const Eigen::ArrayXi& ddni, const Eigen::ArrayXi& ddncs, const Eigen::ArrayXi& ncs, const int& nthread);
RcppExport SEXP _AsyPeer_fdataML(SEXP ySEXP, SEXP XSEXP, SEXP groupSEXP, SEXP IDiSEXP, SEXP gijSEXP, SEXP idpeerSEXP, SEXP ddniSEXP, SEXP ddncsSEXP, SEXP ncsSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type IDi(IDiSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXd>& >::type gij(gijSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type idpeer(idpeerSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddni(ddniSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddncs(ddncsSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ncs(ncsSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fdataML(y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fInstChecky
Eigen::ArrayXXd fInstChecky(const Eigen::ArrayXXd& rhoddX, const Eigen::ArrayXi& ddni, const int& nthread);
RcppExport SEXP _AsyPeer_fInstChecky(SEXP rhoddXSEXP, SEXP ddniSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type rhoddX(rhoddXSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddni(ddniSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fInstChecky(rhoddX, ddni, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fAsyMain
Rcpp::List fAsyMain(const double betal0, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X, Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nc_gamma, const int& dfiso, const int& dfniso, const int& HAC, const int& weight, const int& S, const int& maxit, const double& eps_f, const double& eps_g, const bool& spillover);
RcppExport SEXP _AsyPeer_fAsyMain(SEXP betal0SEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP XSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP nc_gammaSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP weightSEXP, SEXP SSEXP, SEXP maxitSEXP, SEXP eps_fSEXP, SEXP eps_gSEXP, SEXP spilloverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal0(betal0SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const int& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps_g(eps_gSEXP);
    Rcpp::traits::input_parameter< const bool& >::type spillover(spilloverSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyMain(betal0, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, weight, S, maxit, eps_f, eps_g, spillover));
    return rcpp_result_gen;
END_RCPP
}
// fNashE
int fNashE(Eigen::Map<Eigen::VectorXd> y, const Eigen::ArrayXd& alpha, const std::vector<Eigen::MatrixXd>& G, const Eigen::ArrayXd& peffects, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const std::vector<Eigen::ArrayXi>& idpeer, const Eigen::ArrayXi& d, const int& ngroup, const double& tol, const int& maxit, const unsigned int& nthread, const bool& print);
RcppExport SEXP _AsyPeer_fNashE(SEXP ySEXP, SEXP alphaSEXP, SEXP GSEXP, SEXP peffectsSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP idpeerSEXP, SEXP dSEXP, SEXP ngroupSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP nthreadSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type peffects(peffectsSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type idpeer(idpeerSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    Rcpp::traits::input_parameter< const bool& >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(fNashE(y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AsyPeer_fnthreads", (DL_FUNC) &_AsyPeer_fnthreads, 1},
    {"_AsyPeer_highlowstat1", (DL_FUNC) &_AsyPeer_highlowstat1, 6},
    {"_AsyPeer_highlowstat2", (DL_FUNC) &_AsyPeer_highlowstat2, 7},
    {"_AsyPeer_peeravgpower", (DL_FUNC) &_AsyPeer_peeravgpower, 6},
    {"_AsyPeer_fcheckrankEigen", (DL_FUNC) &_AsyPeer_fcheckrankEigen, 2},
    {"_AsyPeer_fassignfold", (DL_FUNC) &_AsyPeer_fassignfold, 2},
    {"_AsyPeer_Demean_separate", (DL_FUNC) &_AsyPeer_Demean_separate, 5},
    {"_AsyPeer_Demean_common", (DL_FUNC) &_AsyPeer_Demean_common, 3},
    {"_AsyPeer_fGnormalise", (DL_FUNC) &_AsyPeer_fGnormalise, 2},
    {"_AsyPeer_fFstat", (DL_FUNC) &_AsyPeer_fFstat, 6},
    {"_AsyPeer_fKPstat", (DL_FUNC) &_AsyPeer_fKPstat, 6},
    {"_AsyPeer_fCESdata", (DL_FUNC) &_AsyPeer_fCESdata, 20},
    {"_AsyPeer_fCESplotdata", (DL_FUNC) &_AsyPeer_fCESplotdata, 24},
    {"_AsyPeer_fCESMain", (DL_FUNC) &_AsyPeer_fCESMain, 32},
    {"_AsyPeer_fdataML", (DL_FUNC) &_AsyPeer_fdataML, 10},
    {"_AsyPeer_fInstChecky", (DL_FUNC) &_AsyPeer_fInstChecky, 3},
    {"_AsyPeer_fAsyMain", (DL_FUNC) &_AsyPeer_fAsyMain, 19},
    {"_AsyPeer_fNashE", (DL_FUNC) &_AsyPeer_fNashE, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_AsyPeer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
