// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fnthreads
int fnthreads(const int& nthread);
RcppExport SEXP _AsyPeer_fnthreads(SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fnthreads(nthread));
    return rcpp_result_gen;
END_RCPP
}
// highlowstat1
List highlowstat1(const Eigen::MatrixXd& X, const std::vector<Eigen::ArrayXXd>& G, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int& ngroup, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_highlowstat1(SEXP XSEXP, SEXP GSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP ngroupSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(highlowstat1(X, G, cumsn, nvec, ngroup, nthread));
    return rcpp_result_gen;
END_RCPP
}
// highlowstat2
List highlowstat2(const Eigen::VectorXd& y, const Eigen::MatrixXd& X, const std::vector<Eigen::ArrayXXd>& G, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int ngroup, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_highlowstat2(SEXP ySEXP, SEXP XSEXP, SEXP GSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP ngroupSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(highlowstat2(y, X, G, cumsn, nvec, ngroup, nthread));
    return rcpp_result_gen;
END_RCPP
}
// peeravgpower
Eigen::MatrixXd peeravgpower(const std::vector<Eigen::MatrixXd>& G, const Eigen::MatrixXd& V, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const int& power, const int& nthread);
RcppExport SEXP _AsyPeer_peeravgpower(SEXP GSEXP, SEXP VSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP powerSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const int& >::type power(powerSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(peeravgpower(G, V, cumsn, nvec, power, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fcheckrankEigen
Eigen::Array<bool, Eigen::Dynamic, 1> fcheckrankEigen(const Eigen::MatrixXd& X, const double& tol);
RcppExport SEXP _AsyPeer_fcheckrankEigen(SEXP XSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fcheckrankEigen(X, tol));
    return rcpp_result_gen;
END_RCPP
}
// fassignfold
Eigen::ArrayXi fassignfold(const Eigen::ArrayXi& subnetwork, const int& nfold, const unsigned long long& seed);
RcppExport SEXP _AsyPeer_fassignfold(SEXP subnetworkSEXP, SEXP nfoldSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type subnetwork(subnetworkSEXP);
    Rcpp::traits::input_parameter< const int& >::type nfold(nfoldSEXP);
    Rcpp::traits::input_parameter< const unsigned long long& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(fassignfold(subnetwork, nfold, seed));
    return rcpp_result_gen;
END_RCPP
}
// Demean_separate
Eigen::ArrayXXd Demean_separate(const Eigen::ArrayXXd& X, const Eigen::ArrayXi& cumsn, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const int& nthread);
RcppExport SEXP _AsyPeer_Demean_separate(SEXP XSEXP, SEXP cumsnSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Demean_separate(X, cumsn, lIso, lnIso, nthread));
    return rcpp_result_gen;
END_RCPP
}
// Demean_common
Eigen::ArrayXXd Demean_common(const Eigen::ArrayXXd& X, const Eigen::ArrayXi& cumsn, const int& nthread);
RcppExport SEXP _AsyPeer_Demean_common(SEXP XSEXP, SEXP cumsnSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(Demean_common(X, cumsn, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fGnormalise
std::vector<Eigen::ArrayXXd> fGnormalise(std::vector<Eigen::ArrayXXd>& G, const int& nthread);
RcppExport SEXP _AsyPeer_fGnormalise(SEXP GSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fGnormalise(G, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fCESdata
Eigen::ArrayXXd fCESdata(const Eigen::ArrayXXd& X, const Eigen::ArrayXd& y, const Eigen::ArrayXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const int& n, const int& Kx, const int& S, const double& rho, const bool& FE, const bool& deriv, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_fCESdata(SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP nSEXP, SEXP KxSEXP, SEXP SSEXP, SEXP rhoSEXP, SEXP FESEXP, SEXP derivSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const bool& >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESdata(X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, nvec, yFMiMa, zFMiMa, n, Kx, S, rho, FE, deriv, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fCESobjrho
double fCESobjrho(const double& beta, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z, const Eigen::ArrayXi& nIso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& sel, const int& n, const int& S);
RcppExport SEXP _AsyPeer_fCESobjrho(SEXP betaSEXP, SEXP ySEXP, SEXP GySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP nIsoSEXP, SEXP WSEXP, SEXP selSEXP, SEXP nSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESobjrho(beta, y, Gy, X, Z, nIso, W, sel, n, S));
    return rcpp_result_gen;
END_RCPP
}
// fCESparmrho
Eigen::VectorXd fCESparmrho(const double& beta, const double& rho, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z, const Eigen::ArrayXi& nIso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& sel, const int& n, const int& S);
RcppExport SEXP _AsyPeer_fCESparmrho(SEXP betaSEXP, SEXP rhoSEXP, SEXP ySEXP, SEXP GySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP nIsoSEXP, SEXP WSEXP, SEXP selSEXP, SEXP nSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESparmrho(beta, rho, y, Gy, X, Z, nIso, W, sel, n, S));
    return rcpp_result_gen;
END_RCPP
}
// fCESobj
double fCESobj(const Eigen::VectorXd& theta01, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::VectorXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const Eigen::MatrixXd& W, const Eigen::ArrayXi& idXiso, const Eigen::ArrayXi& idXniso, const Eigen::ArrayXi& sel, const bool& FE, const double& rhomin, const double& rhomax);
RcppExport SEXP _AsyPeer_fCESobj(SEXP theta01SEXP, SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP WSEXP, SEXP idXisoSEXP, SEXP idXnisoSEXP, SEXP selSEXP, SEXP FESEXP, SEXP rhominSEXP, SEXP rhomaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta01(theta01SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXiso(idXisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXniso(idXnisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const double& >::type rhomin(rhominSEXP);
    Rcpp::traits::input_parameter< const double& >::type rhomax(rhomaxSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESobj(theta01, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, rhomin, rhomax));
    return rcpp_result_gen;
END_RCPP
}
// fCESparm
Eigen::VectorXd fCESparm(const Eigen::VectorXd& theta01, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::VectorXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const Eigen::MatrixXd& W, const Eigen::ArrayXi& idXiso, const Eigen::ArrayXi& idXniso, const Eigen::ArrayXi& sel, const bool& FE);
RcppExport SEXP _AsyPeer_fCESparm(SEXP theta01SEXP, SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP WSEXP, SEXP idXisoSEXP, SEXP idXnisoSEXP, SEXP selSEXP, SEXP FESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta01(theta01SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXiso(idXisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXniso(idXnisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    rcpp_result_gen = Rcpp::wrap(fCESparm(theta01, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE));
    return rcpp_result_gen;
END_RCPP
}
// fCESWeight_1ins
Eigen::MatrixXd fCESWeight_1ins(const Eigen::VectorXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& sel, const int& n, const int& S, const int& Kx, const int& Kz, const int& HACn, const int& dfiso, const int& dfniso);
RcppExport SEXP _AsyPeer_fCESWeight_1ins(SEXP thetaSEXP, SEXP ySEXP, SEXP GySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP selSEXP, SEXP nSEXP, SEXP SSEXP, SEXP KxSEXP, SEXP KzSEXP, SEXP HACnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kz(KzSEXP);
    Rcpp::traits::input_parameter< const int& >::type HACn(HACnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESWeight_1ins(theta, y, Gy, X, Z, Iso, nIso, lIso, lnIso, sel, n, S, Kx, Kz, HACn, dfiso, dfniso));
    return rcpp_result_gen;
END_RCPP
}
// fCESWeight_2ins
Eigen::MatrixXd fCESWeight_2ins(const Eigen::VectorXd& theta, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::VectorXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const Eigen::MatrixXd& W, const Eigen::ArrayXi& idXiso, const Eigen::ArrayXi& idXniso, const Eigen::ArrayXi& sel, const bool& FE, const int& HACn, const int& dfiso, const int& dfniso, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_fCESWeight_2ins(SEXP thetaSEXP, SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP WSEXP, SEXP idXisoSEXP, SEXP idXnisoSEXP, SEXP selSEXP, SEXP FESEXP, SEXP HACnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXiso(idXisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXniso(idXnisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const int& >::type HACn(HACnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESWeight_2ins(theta, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, HACn, dfiso, dfniso, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fCESparmCovrho
Rcpp::List fCESparmCovrho(const Eigen::VectorXd& theta, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::MatrixXd& W, const Eigen::ArrayXi& sel, const int& n, const int& S, const int& Kx, const int& Kz, const int& HACn, const int& dfiso, const int& dfniso);
RcppExport SEXP _AsyPeer_fCESparmCovrho(SEXP thetaSEXP, SEXP ySEXP, SEXP GySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP WSEXP, SEXP selSEXP, SEXP nSEXP, SEXP SSEXP, SEXP KxSEXP, SEXP KzSEXP, SEXP HACnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kx(KxSEXP);
    Rcpp::traits::input_parameter< const int& >::type Kz(KzSEXP);
    Rcpp::traits::input_parameter< const int& >::type HACn(HACnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESparmCovrho(theta, y, Gy, X, Z, Iso, nIso, lIso, lnIso, W, sel, n, S, Kx, Kz, HACn, dfiso, dfniso));
    return rcpp_result_gen;
END_RCPP
}
// fCESparmCov
Rcpp::List fCESparmCov(const Eigen::VectorXd& theta, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::VectorXd& z, const std::vector<Eigen::ArrayXXd>& G, const std::vector<Eigen::ArrayXi>& friendindex, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& frzeroy, const Eigen::ArrayXi& frzeroz, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nvec, const Eigen::ArrayXXd& yFMiMa, const Eigen::ArrayXXd& zFMiMa, const Eigen::MatrixXd& W, const Eigen::ArrayXi& idXiso, const Eigen::ArrayXi& idXniso, const Eigen::ArrayXi& sel, const bool& FE, const int& HACn, const int& dfiso, const int& dfniso, const unsigned int& nthread);
RcppExport SEXP _AsyPeer_fCESparmCov(SEXP thetaSEXP, SEXP XSEXP, SEXP ySEXP, SEXP zSEXP, SEXP GSEXP, SEXP friendindexSEXP, SEXP cumsnSEXP, SEXP frzeroySEXP, SEXP frzerozSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nvecSEXP, SEXP yFMiMaSEXP, SEXP zFMiMaSEXP, SEXP WSEXP, SEXP idXisoSEXP, SEXP idXnisoSEXP, SEXP selSEXP, SEXP FESEXP, SEXP HACnSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type friendindex(friendindexSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroy(frzeroySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type frzeroz(frzerozSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type yFMiMa(yFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type zFMiMa(zFMiMaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXiso(idXisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type idXniso(idXnisoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type sel(selSEXP);
    Rcpp::traits::input_parameter< const bool& >::type FE(FESEXP);
    Rcpp::traits::input_parameter< const int& >::type HACn(HACnSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fCESparmCov(theta, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, HACn, dfiso, dfniso, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fdataML
Rcpp::List fdataML(const Eigen::ArrayXd& y, const Eigen::ArrayXXd& X, const Eigen::ArrayXi& group, const Eigen::ArrayXi& IDi, const std::vector<Eigen::ArrayXd>& gij, const std::vector<Eigen::ArrayXi>& idpeer, const Eigen::ArrayXi& ddni, const Eigen::ArrayXi& ddncs, const Eigen::ArrayXi& ncs, const int& nthread);
RcppExport SEXP _AsyPeer_fdataML(SEXP ySEXP, SEXP XSEXP, SEXP groupSEXP, SEXP IDiSEXP, SEXP gijSEXP, SEXP idpeerSEXP, SEXP ddniSEXP, SEXP ddncsSEXP, SEXP ncsSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type IDi(IDiSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXd>& >::type gij(gijSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type idpeer(idpeerSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddni(ddniSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddncs(ddncsSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ncs(ncsSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fdataML(y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fInstChecky
Eigen::ArrayXXd fInstChecky(const Eigen::ArrayXXd& rhoddX, const Eigen::ArrayXi& ddni, const int& nthread);
RcppExport SEXP _AsyPeer_fInstChecky(SEXP rhoddXSEXP, SEXP ddniSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type rhoddX(rhoddXSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type ddni(ddniSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fInstChecky(rhoddX, ddni, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fV
Eigen::MatrixXd fV(const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& nc_gamma, const bool& spillover);
RcppExport SEXP _AsyPeer_fV(SEXP endoSEXP, SEXP XSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP nc_gammaSEXP, SEXP spilloverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type spillover(spilloverSEXP);
    rcpp_result_gen = Rcpp::wrap(fV(endo, X, Iso, nIso, nc_gamma, spillover));
    return rcpp_result_gen;
END_RCPP
}
// fAsyobj
double fAsyobj(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const Eigen::ArrayXi& nIso);
RcppExport SEXP _AsyPeer_fAsyobj(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP VSEXP, SEXP WSEXP, SEXP nIsoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyobj(betal, Z, y, V, W, nIso));
    return rcpp_result_gen;
END_RCPP
}
// fAsyobj_nospill
double fAsyobj_nospill(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const Eigen::ArrayXi& nIso);
RcppExport SEXP _AsyPeer_fAsyobj_nospill(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP GySEXP, SEXP VSEXP, SEXP WSEXP, SEXP nIsoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyobj_nospill(betal, Z, y, Gy, V, W, nIso));
    return rcpp_result_gen;
END_RCPP
}
// fGmmEstim
Rcpp::List fGmmEstim(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const Eigen::ArrayXi& nIso);
RcppExport SEXP _AsyPeer_fGmmEstim(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP VSEXP, SEXP WSEXP, SEXP nIsoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    rcpp_result_gen = Rcpp::wrap(fGmmEstim(betal, Z, y, V, W, nIso));
    return rcpp_result_gen;
END_RCPP
}
// fGmmEstim_nospill
Rcpp::List fGmmEstim_nospill(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const Eigen::ArrayXi& nIso);
RcppExport SEXP _AsyPeer_fGmmEstim_nospill(SEXP betalSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP GySEXP, SEXP VSEXP, SEXP WSEXP, SEXP nIsoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    rcpp_result_gen = Rcpp::wrap(fGmmEstim_nospill(betal, Z, y, Gy, V, W, nIso));
    return rcpp_result_gen;
END_RCPP
}
// fAsyWopt
Eigen::MatrixXd fAsyWopt(const Eigen::VectorXd& theta, const Eigen::MatrixXd& Z, const Eigen::VectorXd& eta, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const int& dfiso, const int& dfniso, const int& HAC, const int& S);
RcppExport SEXP _AsyPeer_fAsyWopt(SEXP thetaSEXP, SEXP ZSEXP, SEXP etaSEXP, SEXP cumsnSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyWopt(theta, Z, eta, cumsn, Iso, nIso, dfiso, dfniso, HAC, S));
    return rcpp_result_gen;
END_RCPP
}
// fAsyparms
Rcpp::List fAsyparms(const Eigen::VectorXd& theta, const Eigen::MatrixXd& V, const Eigen::VectorXd& sVphi, const Eigen::VectorXd& eta, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X, const Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nc_gamma, const int& dfiso, const int& dfniso, const int& HAC, const int& S);
RcppExport SEXP _AsyPeer_fAsyparms(SEXP thetaSEXP, SEXP VSEXP, SEXP sVphiSEXP, SEXP etaSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP XSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP nc_gammaSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sVphi(sVphiSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyparms(theta, V, sVphi, eta, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, S));
    return rcpp_result_gen;
END_RCPP
}
// fAsyparms_nospill
Rcpp::List fAsyparms_nospill(const Eigen::VectorXd& theta, const Eigen::MatrixXd& V, const Eigen::VectorXd& sVphi, const Eigen::VectorXd& eta, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& endo, const Eigen::MatrixXd& X, const Eigen::MatrixXd& W, const Eigen::ArrayXi& Iso, const Eigen::ArrayXi& nIso, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nc_gamma, const int& dfiso, const int& dfniso, const int& HAC, const int& S);
RcppExport SEXP _AsyPeer_fAsyparms_nospill(SEXP thetaSEXP, SEXP VSEXP, SEXP sVphiSEXP, SEXP etaSEXP, SEXP ZSEXP, SEXP ySEXP, SEXP endoSEXP, SEXP XSEXP, SEXP WSEXP, SEXP IsoSEXP, SEXP nIsoSEXP, SEXP cumsnSEXP, SEXP nc_gammaSEXP, SEXP dfisoSEXP, SEXP dfnisoSEXP, SEXP HACSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type sVphi(sVphiSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type Iso(IsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nIso(nIsoSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nc_gamma(nc_gammaSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfiso(dfisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfniso(dfnisoSEXP);
    Rcpp::traits::input_parameter< const int& >::type HAC(HACSEXP);
    Rcpp::traits::input_parameter< const int& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyparms_nospill(theta, V, sVphi, eta, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, S));
    return rcpp_result_gen;
END_RCPP
}
// fbt
Rcpp::List fbt(const Eigen::VectorXd& Zeta0, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::MatrixXd& V, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const bool& spillover, const unsigned long long& seed);
RcppExport SEXP _AsyPeer_fbt(SEXP Zeta0SEXP, SEXP ZSEXP, SEXP ySEXP, SEXP VSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP spilloverSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zeta0(Zeta0SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type spillover(spilloverSEXP);
    Rcpp::traits::input_parameter< const unsigned long long& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(fbt(Zeta0, Z, y, V, lIso, lnIso, spillover, seed));
    return rcpp_result_gen;
END_RCPP
}
// f_nospillbt
Rcpp::List f_nospillbt(const Eigen::VectorXd& Zeta0, const Eigen::MatrixXd& Z, const Eigen::VectorXd& y, const Eigen::VectorXd& Gy, const Eigen::MatrixXd& V, const std::vector<Eigen::ArrayXi>& lIso, const std::vector<Eigen::ArrayXi>& lnIso, const bool& spillover, const unsigned long long& seed);
RcppExport SEXP _AsyPeer_f_nospillbt(SEXP Zeta0SEXP, SEXP ZSEXP, SEXP ySEXP, SEXP GySEXP, SEXP VSEXP, SEXP lIsoSEXP, SEXP lnIsoSEXP, SEXP spilloverSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zeta0(Zeta0SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Gy(GySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lIso(lIsoSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type lnIso(lnIsoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type spillover(spilloverSEXP);
    Rcpp::traits::input_parameter< const unsigned long long& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(f_nospillbt(Zeta0, Z, y, Gy, V, lIso, lnIso, spillover, seed));
    return rcpp_result_gen;
END_RCPP
}
// fAsyobjbt
double fAsyobjbt(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& Zty, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const int& n_nIso);
RcppExport SEXP _AsyPeer_fAsyobjbt(SEXP betalSEXP, SEXP ZSEXP, SEXP ZtySEXP, SEXP VSEXP, SEXP WSEXP, SEXP n_nIsoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zty(ZtySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_nIso(n_nIsoSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyobjbt(betal, Z, Zty, V, W, n_nIso));
    return rcpp_result_gen;
END_RCPP
}
// fAsyobj_nospillbt
double fAsyobj_nospillbt(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& Zty, const Eigen::VectorXd& ZtGy, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const int& n_nIso);
RcppExport SEXP _AsyPeer_fAsyobj_nospillbt(SEXP betalSEXP, SEXP ZSEXP, SEXP ZtySEXP, SEXP ZtGySEXP, SEXP VSEXP, SEXP WSEXP, SEXP n_nIsoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zty(ZtySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ZtGy(ZtGySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_nIso(n_nIsoSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyobj_nospillbt(betal, Z, Zty, ZtGy, V, W, n_nIso));
    return rcpp_result_gen;
END_RCPP
}
// fAsyparmsbt
Rcpp::List fAsyparmsbt(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& Zty, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const int& n_nIso, const bool& asymmetry);
RcppExport SEXP _AsyPeer_fAsyparmsbt(SEXP betalSEXP, SEXP ZSEXP, SEXP ZtySEXP, SEXP VSEXP, SEXP WSEXP, SEXP n_nIsoSEXP, SEXP asymmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zty(ZtySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_nIso(n_nIsoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type asymmetry(asymmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyparmsbt(betal, Z, Zty, V, W, n_nIso, asymmetry));
    return rcpp_result_gen;
END_RCPP
}
// fAsyparms_nospillbt
Rcpp::List fAsyparms_nospillbt(const double betal, const Eigen::MatrixXd& Z, const Eigen::VectorXd& Zty, const Eigen::VectorXd& ZtGy, const Eigen::MatrixXd& V, const Eigen::MatrixXd& W, const int& n_nIso, const bool& asymmetry);
RcppExport SEXP _AsyPeer_fAsyparms_nospillbt(SEXP betalSEXP, SEXP ZSEXP, SEXP ZtySEXP, SEXP ZtGySEXP, SEXP VSEXP, SEXP WSEXP, SEXP n_nIsoSEXP, SEXP asymmetrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type betal(betalSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zty(ZtySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type ZtGy(ZtGySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_nIso(n_nIsoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type asymmetry(asymmetrySEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyparms_nospillbt(betal, Z, Zty, ZtGy, V, W, n_nIso, asymmetry));
    return rcpp_result_gen;
END_RCPP
}
// fAsyparmsVar_bt
Rcpp::List fAsyparmsVar_bt(const std::vector<std::vector<Eigen::VectorXd>>& outbt, const Eigen::VectorXd& theta0, const Eigen::VectorXd& Zeta0, const bool& asymmetry, const bool& spillover);
RcppExport SEXP _AsyPeer_fAsyparmsVar_bt(SEXP outbtSEXP, SEXP theta0SEXP, SEXP Zeta0SEXP, SEXP asymmetrySEXP, SEXP spilloverSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::vector<Eigen::VectorXd>>& >::type outbt(outbtSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Zeta0(Zeta0SEXP);
    Rcpp::traits::input_parameter< const bool& >::type asymmetry(asymmetrySEXP);
    Rcpp::traits::input_parameter< const bool& >::type spillover(spilloverSEXP);
    rcpp_result_gen = Rcpp::wrap(fAsyparmsVar_bt(outbt, theta0, Zeta0, asymmetry, spillover));
    return rcpp_result_gen;
END_RCPP
}
// fNashE
int fNashE(Eigen::Map<Eigen::VectorXd> y, const Eigen::ArrayXd& alpha, const std::vector<Eigen::MatrixXd>& G, const Eigen::ArrayXd& peffects, const Eigen::ArrayXi& cumsn, const Eigen::ArrayXi& nvec, const std::vector<Eigen::ArrayXi>& idpeer, const Eigen::ArrayXi& d, const int& ngroup, const double& tol, const int& maxit, const unsigned int& nthread, const bool& print);
RcppExport SEXP _AsyPeer_fNashE(SEXP ySEXP, SEXP alphaSEXP, SEXP GSEXP, SEXP peffectsSEXP, SEXP cumsnSEXP, SEXP nvecSEXP, SEXP idpeerSEXP, SEXP dSEXP, SEXP ngroupSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP nthreadSEXP, SEXP printSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXd& >::type peffects(peffectsSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type nvec(nvecSEXP);
    Rcpp::traits::input_parameter< const std::vector<Eigen::ArrayXi>& >::type idpeer(idpeerSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nthread(nthreadSEXP);
    Rcpp::traits::input_parameter< const bool& >::type print(printSEXP);
    rcpp_result_gen = Rcpp::wrap(fNashE(y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print));
    return rcpp_result_gen;
END_RCPP
}
// fFstat
Eigen::ArrayXXd fFstat(const Eigen::MatrixXd& endo, const Eigen::MatrixXd& Z, const int& K, const Eigen::ArrayXi& cumsn, const bool& cluster, const int& nthread);
RcppExport SEXP _AsyPeer_fFstat(SEXP endoSEXP, SEXP ZSEXP, SEXP KSEXP, SEXP cumsnSEXP, SEXP clusterSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const bool& >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fFstat(endo, Z, K, cumsn, cluster, nthread));
    return rcpp_result_gen;
END_RCPP
}
// fKPstat
Eigen::ArrayXXd fKPstat(const Eigen::MatrixXd& endo, const Eigen::MatrixXd& Z, const int& K, const Eigen::ArrayXi& cumsn, const bool& cluster);
RcppExport SEXP _AsyPeer_fKPstat(SEXP endoSEXP, SEXP ZSEXP, SEXP KSEXP, SEXP cumsnSEXP, SEXP clusterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXi& >::type cumsn(cumsnSEXP);
    Rcpp::traits::input_parameter< const bool& >::type cluster(clusterSEXP);
    rcpp_result_gen = Rcpp::wrap(fKPstat(endo, Z, K, cumsn, cluster));
    return rcpp_result_gen;
END_RCPP
}
// fswstat
Eigen::ArrayXXd fswstat(const Eigen::MatrixXd& endo, const Eigen::MatrixXd& Z, const int& K, const int& nthread);
RcppExport SEXP _AsyPeer_fswstat(SEXP endoSEXP, SEXP ZSEXP, SEXP KSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type endo(endoSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(fswstat(endo, Z, K, nthread));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AsyPeer_fnthreads", (DL_FUNC) &_AsyPeer_fnthreads, 1},
    {"_AsyPeer_highlowstat1", (DL_FUNC) &_AsyPeer_highlowstat1, 6},
    {"_AsyPeer_highlowstat2", (DL_FUNC) &_AsyPeer_highlowstat2, 7},
    {"_AsyPeer_peeravgpower", (DL_FUNC) &_AsyPeer_peeravgpower, 6},
    {"_AsyPeer_fcheckrankEigen", (DL_FUNC) &_AsyPeer_fcheckrankEigen, 2},
    {"_AsyPeer_fassignfold", (DL_FUNC) &_AsyPeer_fassignfold, 3},
    {"_AsyPeer_Demean_separate", (DL_FUNC) &_AsyPeer_Demean_separate, 5},
    {"_AsyPeer_Demean_common", (DL_FUNC) &_AsyPeer_Demean_common, 3},
    {"_AsyPeer_fGnormalise", (DL_FUNC) &_AsyPeer_fGnormalise, 2},
    {"_AsyPeer_fCESdata", (DL_FUNC) &_AsyPeer_fCESdata, 20},
    {"_AsyPeer_fCESobjrho", (DL_FUNC) &_AsyPeer_fCESobjrho, 10},
    {"_AsyPeer_fCESparmrho", (DL_FUNC) &_AsyPeer_fCESparmrho, 11},
    {"_AsyPeer_fCESobj", (DL_FUNC) &_AsyPeer_fCESobj, 23},
    {"_AsyPeer_fCESparm", (DL_FUNC) &_AsyPeer_fCESparm, 21},
    {"_AsyPeer_fCESWeight_1ins", (DL_FUNC) &_AsyPeer_fCESWeight_1ins, 17},
    {"_AsyPeer_fCESWeight_2ins", (DL_FUNC) &_AsyPeer_fCESWeight_2ins, 25},
    {"_AsyPeer_fCESparmCovrho", (DL_FUNC) &_AsyPeer_fCESparmCovrho, 18},
    {"_AsyPeer_fCESparmCov", (DL_FUNC) &_AsyPeer_fCESparmCov, 25},
    {"_AsyPeer_fdataML", (DL_FUNC) &_AsyPeer_fdataML, 10},
    {"_AsyPeer_fInstChecky", (DL_FUNC) &_AsyPeer_fInstChecky, 3},
    {"_AsyPeer_fV", (DL_FUNC) &_AsyPeer_fV, 6},
    {"_AsyPeer_fAsyobj", (DL_FUNC) &_AsyPeer_fAsyobj, 6},
    {"_AsyPeer_fAsyobj_nospill", (DL_FUNC) &_AsyPeer_fAsyobj_nospill, 7},
    {"_AsyPeer_fGmmEstim", (DL_FUNC) &_AsyPeer_fGmmEstim, 6},
    {"_AsyPeer_fGmmEstim_nospill", (DL_FUNC) &_AsyPeer_fGmmEstim_nospill, 7},
    {"_AsyPeer_fAsyWopt", (DL_FUNC) &_AsyPeer_fAsyWopt, 10},
    {"_AsyPeer_fAsyparms", (DL_FUNC) &_AsyPeer_fAsyparms, 17},
    {"_AsyPeer_fAsyparms_nospill", (DL_FUNC) &_AsyPeer_fAsyparms_nospill, 17},
    {"_AsyPeer_fbt", (DL_FUNC) &_AsyPeer_fbt, 8},
    {"_AsyPeer_f_nospillbt", (DL_FUNC) &_AsyPeer_f_nospillbt, 9},
    {"_AsyPeer_fAsyobjbt", (DL_FUNC) &_AsyPeer_fAsyobjbt, 6},
    {"_AsyPeer_fAsyobj_nospillbt", (DL_FUNC) &_AsyPeer_fAsyobj_nospillbt, 7},
    {"_AsyPeer_fAsyparmsbt", (DL_FUNC) &_AsyPeer_fAsyparmsbt, 7},
    {"_AsyPeer_fAsyparms_nospillbt", (DL_FUNC) &_AsyPeer_fAsyparms_nospillbt, 8},
    {"_AsyPeer_fAsyparmsVar_bt", (DL_FUNC) &_AsyPeer_fAsyparmsVar_bt, 5},
    {"_AsyPeer_fNashE", (DL_FUNC) &_AsyPeer_fNashE, 13},
    {"_AsyPeer_fFstat", (DL_FUNC) &_AsyPeer_fFstat, 6},
    {"_AsyPeer_fKPstat", (DL_FUNC) &_AsyPeer_fKPstat, 5},
    {"_AsyPeer_fswstat", (DL_FUNC) &_AsyPeer_fswstat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AsyPeer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
