# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combn <- function(elements, n, k) {
    .Call(`_AsyPeer_combn`, elements, n, k)
}

BRSingle <- function(alpha, y, G, betadelta, n, idpeer, d) {
    .Call(`_AsyPeer_BRSingle`, alpha, y, G, betadelta, n, idpeer, d)
}

NashSingle <- function(y0, alpha, G, betadelta, idpeer, d, tol) {
    .Call(`_AsyPeer_NashSingle`, y0, alpha, G, betadelta, idpeer, d, tol)
}

falpha <- function(betadelta, G, y, isolates) {
    .Call(`_AsyPeer_falpha`, betadelta, G, y, isolates)
}

fRankSym <- function(beta, delta, betadelta, y, alpha, G, idpeer, treat, d, isolates, tol, nthread) {
    .Call(`_AsyPeer_fRankSym`, beta, delta, betadelta, y, alpha, G, idpeer, treat, d, isolates, tol, nthread)
}

fRankASym <- function(y, alpha, betadelta, G, idpeer, treat, d, tol, nthread, seed, print) {
    .Call(`_AsyPeer_fRankASym`, y, alpha, betadelta, G, idpeer, treat, d, tol, nthread, seed, print)
}

fnthreads <- function(nthread) {
    .Call(`_AsyPeer_fnthreads`, nthread)
}

highlowstat1 <- function(X, G, cumsn, nvec, ngroup, nthread) {
    .Call(`_AsyPeer_highlowstat1`, X, G, cumsn, nvec, ngroup, nthread)
}

highlowstat2 <- function(y, X, G, cumsn, nvec, ngroup, nthread) {
    .Call(`_AsyPeer_highlowstat2`, y, X, G, cumsn, nvec, ngroup, nthread)
}

peeravgpower <- function(G, V, cumsn, nvec, power, nthread) {
    .Call(`_AsyPeer_peeravgpower`, G, V, cumsn, nvec, power, nthread)
}

fcheckrankEigen <- function(X, tol = 1e-10) {
    .Call(`_AsyPeer_fcheckrankEigen`, X, tol)
}

fassignfold <- function(subnetwork, nfold, seed) {
    .Call(`_AsyPeer_fassignfold`, subnetwork, nfold, seed)
}

Demean_separate <- function(X, cumsn, lIso, lnIso, nthread) {
    .Call(`_AsyPeer_Demean_separate`, X, cumsn, lIso, lnIso, nthread)
}

Demean_common <- function(X, cumsn, nthread) {
    .Call(`_AsyPeer_Demean_common`, X, cumsn, nthread)
}

fGnormalise <- function(G, nthread = 1L) {
    .Call(`_AsyPeer_fGnormalise`, G, nthread)
}

fCESdata <- function(X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, nvec, yFMiMa, zFMiMa, n, Kx, S, rho, FE, deriv, nthread) {
    .Call(`_AsyPeer_fCESdata`, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, nvec, yFMiMa, zFMiMa, n, Kx, S, rho, FE, deriv, nthread)
}

fCESobjrho <- function(beta, y, Gy, X, Z, nIso, W, sel, n, S) {
    .Call(`_AsyPeer_fCESobjrho`, beta, y, Gy, X, Z, nIso, W, sel, n, S)
}

fCESparmrho <- function(beta, rho, y, Gy, X, Z, nIso, W, sel, n, S) {
    .Call(`_AsyPeer_fCESparmrho`, beta, rho, y, Gy, X, Z, nIso, W, sel, n, S)
}

fCESobj <- function(theta01, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, rhomin, rhomax) {
    .Call(`_AsyPeer_fCESobj`, theta01, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, rhomin, rhomax)
}

fCESparm <- function(theta01, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE) {
    .Call(`_AsyPeer_fCESparm`, theta01, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE)
}

fCESWeight_1ins <- function(theta, y, Gy, X, Z, Iso, nIso, lIso, lnIso, sel, n, S, Kx, Kz, HACn, dfiso, dfniso) {
    .Call(`_AsyPeer_fCESWeight_1ins`, theta, y, Gy, X, Z, Iso, nIso, lIso, lnIso, sel, n, S, Kx, Kz, HACn, dfiso, dfniso)
}

fCESWeight_2ins <- function(theta, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, HACn, dfiso, dfniso, nthread) {
    .Call(`_AsyPeer_fCESWeight_2ins`, theta, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, HACn, dfiso, dfniso, nthread)
}

fCESparmCovrho <- function(theta, y, Gy, X, Z, Iso, nIso, lIso, lnIso, W, sel, n, S, Kx, Kz, HACn, dfiso, dfniso) {
    .Call(`_AsyPeer_fCESparmCovrho`, theta, y, Gy, X, Z, Iso, nIso, lIso, lnIso, W, sel, n, S, Kx, Kz, HACn, dfiso, dfniso)
}

fCESparmCov <- function(theta, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, HACn, dfiso, dfniso, nthread) {
    .Call(`_AsyPeer_fCESparmCov`, theta, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, W, idXiso, idXniso, sel, FE, HACn, dfiso, dfniso, nthread)
}

fdataML <- function(y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread) {
    .Call(`_AsyPeer_fdataML`, y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread)
}

fInstChecky <- function(rhoddX, ddni, nthread) {
    .Call(`_AsyPeer_fInstChecky`, rhoddX, ddni, nthread)
}

fV <- function(endo, X, Iso, nIso, nc_gamma, spillover) {
    .Call(`_AsyPeer_fV`, endo, X, Iso, nIso, nc_gamma, spillover)
}

fAsyobj <- function(betal, Z, y, V, W, nIso) {
    .Call(`_AsyPeer_fAsyobj`, betal, Z, y, V, W, nIso)
}

fAsyobj_nospill <- function(betal, Z, y, Gy, V, W, nIso) {
    .Call(`_AsyPeer_fAsyobj_nospill`, betal, Z, y, Gy, V, W, nIso)
}

fGmmEstim <- function(betal, Z, y, V, W, nIso) {
    .Call(`_AsyPeer_fGmmEstim`, betal, Z, y, V, W, nIso)
}

fGmmEstim_nospill <- function(betal, Z, y, Gy, V, W, nIso) {
    .Call(`_AsyPeer_fGmmEstim_nospill`, betal, Z, y, Gy, V, W, nIso)
}

fAsyWopt <- function(theta, Z, eta, cumsn, Iso, nIso, dfiso, dfniso, HAC, S) {
    .Call(`_AsyPeer_fAsyWopt`, theta, Z, eta, cumsn, Iso, nIso, dfiso, dfniso, HAC, S)
}

fAsyparms <- function(theta, V, sVphi, eta, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, S) {
    .Call(`_AsyPeer_fAsyparms`, theta, V, sVphi, eta, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, S)
}

fAsyparms_nospill <- function(theta, V, sVphi, eta, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, S) {
    .Call(`_AsyPeer_fAsyparms_nospill`, theta, V, sVphi, eta, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, S)
}

fbt <- function(Zeta0, Z, y, V, lIso, lnIso, spillover, seed) {
    .Call(`_AsyPeer_fbt`, Zeta0, Z, y, V, lIso, lnIso, spillover, seed)
}

f_nospillbt <- function(Zeta0, Z, y, Gy, V, lIso, lnIso, spillover, seed) {
    .Call(`_AsyPeer_f_nospillbt`, Zeta0, Z, y, Gy, V, lIso, lnIso, spillover, seed)
}

fAsyobjbt <- function(betal, Z, Zty, V, W, n_nIso) {
    .Call(`_AsyPeer_fAsyobjbt`, betal, Z, Zty, V, W, n_nIso)
}

fAsyobj_nospillbt <- function(betal, Z, Zty, ZtGy, V, W, n_nIso) {
    .Call(`_AsyPeer_fAsyobj_nospillbt`, betal, Z, Zty, ZtGy, V, W, n_nIso)
}

fAsyparmsbt <- function(betal, Z, Zty, V, W, n_nIso, asymmetry) {
    .Call(`_AsyPeer_fAsyparmsbt`, betal, Z, Zty, V, W, n_nIso, asymmetry)
}

fAsyparms_nospillbt <- function(betal, Z, Zty, ZtGy, V, W, n_nIso, asymmetry) {
    .Call(`_AsyPeer_fAsyparms_nospillbt`, betal, Z, Zty, ZtGy, V, W, n_nIso, asymmetry)
}

fAsyparmsVar_bt <- function(outbt, theta0, Zeta0, asymmetry, spillover) {
    .Call(`_AsyPeer_fAsyparmsVar_bt`, outbt, theta0, Zeta0, asymmetry, spillover)
}

fNashE <- function(y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print) {
    .Call(`_AsyPeer_fNashE`, y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print)
}

fFstat <- function(endo, Z, K, cumsn, cluster, nthread) {
    .Call(`_AsyPeer_fFstat`, endo, Z, K, cumsn, cluster, nthread)
}

fKPstat <- function(endo, Z, K, cumsn, cluster) {
    .Call(`_AsyPeer_fKPstat`, endo, Z, K, cumsn, cluster)
}

fswstat <- function(endo, Z, K, nthread) {
    .Call(`_AsyPeer_fswstat`, endo, Z, K, nthread)
}

