# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnthreads <- function(nthread) {
    .Call(`_AsyPeer_fnthreads`, nthread)
}

highlowstat1 <- function(X, G, cumsn, nvec, ngroup, nthread) {
    .Call(`_AsyPeer_highlowstat1`, X, G, cumsn, nvec, ngroup, nthread)
}

highlowstat2 <- function(y, X, G, cumsn, nvec, ngroup, nthread) {
    .Call(`_AsyPeer_highlowstat2`, y, X, G, cumsn, nvec, ngroup, nthread)
}

peeravgpower <- function(G, V, cumsn, nvec, power, nthread) {
    .Call(`_AsyPeer_peeravgpower`, G, V, cumsn, nvec, power, nthread)
}

fcheckrankEigen <- function(X, tol = 1e-10) {
    .Call(`_AsyPeer_fcheckrankEigen`, X, tol)
}

fassignfold <- function(ddgroup, nfold) {
    .Call(`_AsyPeer_fassignfold`, ddgroup, nfold)
}

Demean_separate <- function(X, cumsn, lIso, lnIso, nthread) {
    .Call(`_AsyPeer_Demean_separate`, X, cumsn, lIso, lnIso, nthread)
}

Demean_common <- function(X, cumsn, nthread) {
    .Call(`_AsyPeer_Demean_common`, X, cumsn, nthread)
}

fGnormalise <- function(G, nthread = 1L) {
    .Call(`_AsyPeer_fGnormalise`, G, nthread)
}

fFstat <- function(y, X, index, cumsn, HAC, nthread) {
    .Call(`_AsyPeer_fFstat`, y, X, index, cumsn, HAC, nthread)
}

fKPstat <- function(endo_, X, Z_, index, cumsn, HAC = 0L) {
    .Call(`_AsyPeer_fKPstat`, endo_, X, Z_, index, cumsn, HAC)
}

fCESdata <- function(X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, nvec, yFMiMa, zFMiMa, n, Kx, S, rho, FE, deriv, nthread) {
    .Call(`_AsyPeer_fCESdata`, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, nvec, yFMiMa, zFMiMa, n, Kx, S, rho, FE, deriv, nthread)
}

fCESplotdata <- function(gridrho, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, idXiso, idXniso, sel, FE, maxit, eps_f, eps_g, nthread) {
    .Call(`_AsyPeer_fCESplotdata`, gridrho, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, idXiso, idXniso, sel, FE, maxit, eps_f, eps_g, nthread)
}

fCESMain <- function(setrho, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, idXiso, idXniso, sel, n, Kx, S, HACn, dfiso, dfniso, FE, rhomin, rhomax, maxit, eps_f, eps_g, nthread) {
    .Call(`_AsyPeer_fCESMain`, setrho, X, y, z, G, friendindex, cumsn, frzeroy, frzeroz, lIso, lnIso, Iso, nIso, nvec, yFMiMa, zFMiMa, idXiso, idXniso, sel, n, Kx, S, HACn, dfiso, dfniso, FE, rhomin, rhomax, maxit, eps_f, eps_g, nthread)
}

fdataML <- function(y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread) {
    .Call(`_AsyPeer_fdataML`, y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread)
}

fInstChecky <- function(rhoddX, ddni, nthread) {
    .Call(`_AsyPeer_fInstChecky`, rhoddX, ddni, nthread)
}

fAsyMain <- function(betal0, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, weight, S, maxit, eps_f, eps_g, spillover) {
    .Call(`_AsyPeer_fAsyMain`, betal0, Z, y, endo, X, W, Iso, nIso, cumsn, nc_gamma, dfiso, dfniso, HAC, weight, S, maxit, eps_f, eps_g, spillover)
}

fNashE <- function(y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print) {
    .Call(`_AsyPeer_fNashE`, y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print)
}

