# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnthreads <- function(nthread) {
    .Call(`_AsyPeer_fnthreads`, nthread)
}

highlowstat1 <- function(X, G, cumsn, nvec, ngroup, nthread) {
    .Call(`_AsyPeer_highlowstat1`, X, G, cumsn, nvec, ngroup, nthread)
}

highlowstat2 <- function(y, X, G, cumsn, nvec, ngroup, nthread) {
    .Call(`_AsyPeer_highlowstat2`, y, X, G, cumsn, nvec, ngroup, nthread)
}

peeravgpower <- function(G, V, cumsn, nvec, power, nthread) {
    .Call(`_AsyPeer_peeravgpower`, G, V, cumsn, nvec, power, nthread)
}

fcheckrankEigen <- function(X, tol = 1e-10) {
    .Call(`_AsyPeer_fcheckrankEigen`, X, tol)
}

fassignfold <- function(ddgroup, nfold) {
    .Call(`_AsyPeer_fassignfold`, ddgroup, nfold)
}

Demean_separate <- function(X, cumsn, lIso, lnIso, nthread) {
    .Call(`_AsyPeer_Demean_separate`, X, cumsn, lIso, lnIso, nthread)
}

Demean_common <- function(X, cumsn, nthread) {
    .Call(`_AsyPeer_Demean_common`, X, cumsn, nthread)
}

fGnormalise <- function(G, nthread = 1L) {
    .Call(`_AsyPeer_fGnormalise`, G, nthread)
}

fFstat <- function(y, X, index, cumsn, HAC, nthread) {
    .Call(`_AsyPeer_fFstat`, y, X, index, cumsn, HAC, nthread)
}

fKPstat <- function(endo_, X, Z_, index, cumsn, HAC = 0L) {
    .Call(`_AsyPeer_fKPstat`, endo_, X, Z_, index, cumsn, HAC)
}

fdataML <- function(y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread) {
    .Call(`_AsyPeer_fdataML`, y, X, group, IDi, gij, idpeer, ddni, ddncs, ncs, nthread)
}

fInstChecky <- function(rhoddX, ddni, nthread) {
    .Call(`_AsyPeer_fInstChecky`, rhoddX, ddni, nthread)
}

gmm_obj <- function(betal, Z, y, endo, X_iso, X_niso, W, c_gamma, nc_gamma, S) {
    .Call(`_AsyPeer_gmm_obj`, betal, Z, y, endo, X_iso, X_niso, W, c_gamma, nc_gamma, S)
}

gmm_obj_nospil <- function(betal, Z, y, endo, X_iso, X_niso, W, c_gamma, nc_gamma, S) {
    .Call(`_AsyPeer_gmm_obj_nospil`, betal, Z, y, endo, X_iso, X_niso, W, c_gamma, nc_gamma, S)
}

W_optimal <- function(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S) {
    .Call(`_AsyPeer_W_optimal`, betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S)
}

W_optimal_nospil <- function(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S) {
    .Call(`_AsyPeer_W_optimal_nospil`, betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S)
}

compute_estimate <- function(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S) {
    .Call(`_AsyPeer_compute_estimate`, betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S)
}

compute_estimate_nospil <- function(betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S) {
    .Call(`_AsyPeer_compute_estimate_nospil`, betal, Z, y, endo, X_iso, X_niso, W, Iso, nIso, cumsn, dfiso, dfniso, HAC, c_gamma, nc_gamma, S)
}

fNashE <- function(y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print) {
    .Call(`_AsyPeer_fNashE`, y, alpha, G, peffects, cumsn, nvec, idpeer, d, ngroup, tol, maxit, nthread, print)
}

